# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

User.create([
  {email: "sezama03@hotmail.com", password: "holamama", role: 1}
  ])

Content.create(slide_1_title: "A template, infinite possibilities", slide_1_subtitle: "We give you everything done, except the coffee", slide_2_title: "Customization extremes", slide_2_subtitle: "Configure your own template in few easy steps", slide_3_title: "Customization extremes", slide_3_subtitle: "Configure your own template in few easy steps", carousel_link_1_text: "25 default colors", carousel_link_1: "https://www.facebook.com", carousel_link_2_text: "Variables less for all colors", carousel_link_2: "https://www.facebook.com",carousel_link_3_text: "Full width and boxed mode", carousel_link_3: "https://www.facebook.com", feature_1_title: "Lorem ipsum dolor", feature_1_text: "Consectetur adipisicing elit vritatis dolor rem officia molestiae atque eveniet inventore earum quas voluptates cumque", feature_2_title: "Lorem ipsum dolor", feature_2_text: "Consectetur adipisicing elit vritatis dolor rem officia molestiae atque eveniet inventore earum quas voluptates cumque", feature_3_title: "Lorem ipsum dolor", feature_3_text: "Consectetur adipisicing elit vritatis dolor rem officia molestiae atque eveniet inventore earum quas voluptates cumque", feature_4_title: "Lorem ipsum dolor", feature_4_text: "Consectetur adipisicing elit vritatis dolor rem officia molestiae atque eveniet inventore earum quas voluptates cumque", section_1_title: "The template for all devices", section_1_first_paragraph: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quasi, sapiente, nam sunt rem beatae architecto cupiditate numquam consectetur dolorum aliquam suscipit adipisci expedita vel quaerat illum aperiam facere inventore officia.", section_1_second_paragraph: "Consequuntur sed ipsum eius minima eum velit soluta accusamus omnis maiores modi quae mollitia consectetur adipisci.", section_2_title: "The template for all devices", section_2_first_paragraph: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quasi, sapiente, nam sunt rem beatae architecto cupiditate numquam consectetur dolorum aliquam suscipit adipisci expedita vel quaerat illum aperiam facere inventore officia.", section_2_second_paragraph: "Consequuntur sed ipsum eius minima eum velit soluta accusamus omnis maiores modi quae mollitia consectetur adipisci.", section_3_title: "The template for all devices", section_3_first_paragraph: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quasi, sapiente, nam sunt rem beatae architecto cupiditate numquam consectetur dolorum aliquam suscipit adipisci expedita vel quaerat illum aperiam facere inventore officia.", section_3_second_paragraph: "Consequuntur sed ipsum eius minima eum velit soluta accusamus omnis maiores modi quae mollitia consectetur adipisci.")